### PR TITLE
Cleanup and general fixes, expanded GitHub Pages episode

### PR DESCRIPTION
**Pull request by danmichaelo**
Fixed a few things while I worked myself through the material preparing for the Padova workshop on Thursday. Mostly minor things, but I also expanded the GitHub Pages part a bit. See the commit messages for details.

Hope it can be merged before Thursday when I'm doing the workshop :)

### CODE REVIEW

**Comment by drjwbaker** [comment]
@icecjan Can you look at this as well please? :)

**Comment by drjwbaker** [comment]
@icecjan Sorry, ignore the above comment: wrong person!

**Comment by icecjan** [comment]
@drjwbaker *phew* :)

**Comment by danmichaelo** [comment]
Pinging @weaverbel or @jezcope

**Comment by drjwbaker** [comment]
Temp merge to tech lesson: we can revert if needed later!

**Pull request merged**
